Bejebeje.Mvc/Controllers/ArtistController.cs
namespace Bejebeje.Mvc.Controllers;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bejebeje.Common.Extensions;
using Bejebeje.Models.Artist;
using Bejebeje.Mvc.ViewModels.Artists.CreateIndividualArtist;
using Bejebeje.Services.Services.Interfaces;
using Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Formats;
using SixLabors.ImageSharp.PixelFormats;

public class ArtistController : Controller
{
  private readonly IArtistsService _artistsService;

  public ArtistController(IArtistsService artistsService)
  {
    _artistsService = artistsService;
  }

  [Route("artists")]
  public async Task<IActionResult> Index()
  {
    IDictionary<char, List<LibraryArtistViewModel>> viewModel = await _artistsService
      .GetAllArtistsAsync();

    return View(viewModel);
  }

  [Authorize]
  [Route("artists/new/selector")]
  public IActionResult Selector()
  {
    return View();
  }

  [Authorize]
  [Route("artists/new/individual")]
  public IActionResult Create()
  {
    CreateIndividualArtistViewModel viewModel = new();

    return View(viewModel);
  }

  [Authorize]
  [HttpPost]
  [Route("artists/new/individual")]
  public async Task<IActionResult> Create(CreateIndividualArtistViewModel viewModel)
  {
    try
    {
      string userId = User.GetUserId().ToString();
      string firstName = viewModel.FirstName.Trim();
      string lastName = string.IsNullOrEmpty(viewModel.LastName) ? string.Empty : viewModel.LastName.Trim();
      string fullName = string.IsNullOrEmpty(lastName) ? firstName : $"{firstName} {lastName}";
      string artistSlug = fullName.NormalizeStringForUrl();
      var existingArtist = await _artistsService.GetArtistDetailsAsync(artistSlug, userId);

      // check for duplicate
      if (existingArtist != null)
      {
        viewModel.ExistingArtistFullName = fullName;
        viewModel.ExistingArtistSlug = existingArtist.PrimarySlug;
        viewModel.ExistingArtistImageUrl = existingArtist.ImageUrl;
        viewModel.ExistingArtistImageAlternateText = $"Photo of {existingArtist.FullName}";

        ViewBag.ArtistExists = true;
        return View(viewModel);
      }

      string turkishLetters = "ğıİöü";

      bool containsTurkishLetters = fullName.Any(c => turkishLetters.Contains(c, StringComparison.OrdinalIgnoreCase));

      // check for turkish letters
      if (containsTurkishLetters)
      {
        ModelState.AddModelError(string.Empty, "Are you sure you're adding Kurdish artists?");
        return View(viewModel);
      }

      if (viewModel.Photo != null)
      {
        // check image file size
        if (viewModel.Photo is { Length: > 500_000 })
        {
          ModelState.AddModelError(nameof(viewModel.Photo), "The photo size must not exceed 500KB.");
          return View(viewModel);
        }

        using Image<Rgba32> image = await Image.LoadAsync<Rgba32>(viewModel.Photo.OpenReadStream());

        if (image.Width > 1000 || image.Height > 1000)
        {
          ModelState.AddModelError(nameof(viewModel.Photo), "The photo must be at most 1000x1000 pixels.");
          return View(viewModel);
        }
      }

      CreateIndividualArtistDto dto = new()
      {
        FirstName = firstName,
        LastName = lastName,
        UserId = userId,
        Biography = viewModel.Biography.Trim(),
      };

      ArtistCreationResult result = await _artistsService
        .AddArtistAsync(dto);

      return RedirectToAction("ArtistLyrics", "Lyric", new { artistSlug = result.PrimarySlug });
    }
    catch
    {
      return View(viewModel);
    }
  }

  [Authorize]
  [Route("artists/{artistSlug}/update")]
  public async Task<IActionResult> Update(string artistSlug)
  {
    string userId = User.Identity.IsAuthenticated
      ? User.GetUserId().ToString()
      : string.Empty;

    ArtistViewModel artistViewModel = await _artistsService
      .GetArtistDetailsAsync(artistSlug, userId);

    if (string.IsNullOrEmpty(userId) || !artistViewModel.IsOwnSubmission ||
        !((DateTime.UtcNow - artistViewModel.CreatedAt).TotalDays < 2))
    {
      throw new Exception("User does not have access to update the artist.");
    }

    UpdateArtistViewModel viewModel = new UpdateArtistViewModel
    {
      Id = artistViewModel.Id,
      FirstName = artistViewModel.FirstName,
      LastName = artistViewModel.LastName,
    };

    return View(viewModel);
  }

  [Authorize]
  [HttpPost]
  [Route("artists/{artistSlug}/update")]
  public async Task<IActionResult> Update(UpdateArtistViewModel viewModel)
  {
    try
    {
      string userId = User.Identity.IsAuthenticated
        ? User.GetUserId().ToString()
        : string.Empty;

      ArtistViewModel artist = await _artistsService
        .GetArtistDetailsByIdAsync(viewModel.Id, userId);

      if (string.IsNullOrEmpty(userId) || !artist.IsOwnSubmission ||
          !((DateTime.UtcNow - artist.CreatedAt).TotalDays < 2))
      {
        throw new Exception("User does not have access to update the artist.");
      }

      ArtistUpdateResult result = await _artistsService
        .UpdateArtistAsync(viewModel);

      return RedirectToAction("ArtistLyrics", "Lyric", new { artistSlug = result.PrimarySlug });
    }
    catch
    {
      return View(viewModel);
    }
  }
}

Bejebeje.Mvc/Controllers/AuthorController.cs
namespace Bejebeje.Mvc.Controllers;

using System.Threading.Tasks;
using Bejebeje.Models.Author;
using Bejebeje.Services.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

public class AuthorController : Controller
{
  private readonly IAuthorService _authorService;

  public AuthorController(IAuthorService authorService)
  {
    _authorService = authorService;
  }

  [Route("authors/{authorSlug}")]
  public async Task<IActionResult> Get(string authorSlug)
  {
    AuthorDetailsViewModel viewModel = await _authorService.GetAuthorDetailsAsync(authorSlug);

    return View(viewModel);
  }
}

Bejebeje.Mvc/Controllers/LyricController.cs
namespace Bejebeje.Mvc.Controllers;

using System.Threading.Tasks;
using Bejebeje.Models.Artist;
using Bejebeje.Models.Lyric;
using Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Services.Interfaces;

public class LyricController : Controller
{
  private readonly IArtistsService _artistsService;

  private readonly ILyricsService _lyricsService;

  public LyricController(
    IArtistsService artistsService,
    ILyricsService lyricsService)
  {
    _artistsService = artistsService;
    _lyricsService = lyricsService;
  }

  [Route("artists/{artistSlug}/lyrics")]
  public async Task<IActionResult> ArtistLyrics(string artistSlug)
  {
    string userId = User.Identity.IsAuthenticated
      ? User.GetUserId().ToString()
      : string.Empty;

    ArtistLyricsViewModel viewModel = await _lyricsService
      .GetLyricsAsync(artistSlug, userId);

    if (viewModel == null)
    {
      return RedirectToAction("Index", "Home");
    }

    return View(viewModel);
  }

  [Route("artists/{artistSlug}/lyrics/{lyricSlug}")]
  public async Task<IActionResult> Lyric(string artistSlug, string lyricSlug)
  {
    string userId = User.Identity.IsAuthenticated
      ? User.GetUserId().ToString()
      : string.Empty;

    LyricDetailsViewModel viewModel = await _lyricsService
      .GetSingleLyricAsync(artistSlug, lyricSlug, userId);

    viewModel.PrimarySlug = lyricSlug;

    return View(viewModel);
  }

  [Authorize]
  [Route("lyrics/like/{lyricId}")]
  public async Task<IActionResult> Like(string artistSlug, string lyricSlug, int lyricId)
  {
    try
    {
      string userId = User.GetUserId().ToString();

      await _lyricsService.LikeLyricAsync(userId, lyricId);

      return RedirectToAction("Lyric", new { artistSlug, lyricSlug });
    }
    catch
    {
      return RedirectToAction("Lyric", new { artistSlug, lyricSlug });
    }
  }

  [Authorize]
  [HttpGet]
  [Route("artists/{artistSlug}/lyrics/new")]
  public async Task<IActionResult> Create(string artistSlug)
  {
    string userId = User
      .GetUserId()
      .ToString();

    ArtistViewModel artist = await _artistsService
      .GetArtistDetailsAsync(artistSlug, userId);

    CreateLyricViewModel viewModel = new CreateLyricViewModel();
    viewModel.Artist = artist;

    return View(viewModel);
  }

  [Authorize]
  [HttpPost]
  [Route("artists/{artistSlug}/lyrics/new")]
  public async Task<IActionResult> Create(CreateLyricViewModel viewModel)
  {
    string userId = User
      .GetUserId()
      .ToString();

    viewModel.UserId = userId;

    LyricCreateResultViewModel result = await _lyricsService
      .AddLyricAsync(viewModel);

    return RedirectToAction("Like", "Lyric",
      new { artistSlug = result.ArtistSlug, lyricSlug = result.LyricSlug, lyricId = result.LyricId });
  }
}

Bejebeje.Mvc/Views/Lyric/ArtistLyrics.cshtml
@model Bejebeje.Models.Artist.ArtistLyricsViewModel

@{
  ViewData["Title"] = $"{Model.Artist.FullName} lyrics";
  ViewData["Description"] = $"{Model.Artist.FullName} lyrics. Gotinê stranê {Model.Artist.FullName}. {Model.Artist.FullName} sözleri";
}

<div class="py-5 pr-4 mb-6">
  <nav class="text-neutral-200 opacity-70 uppercase text-base">
    <a asp-controller="Artist" asp-action="Index">/ Artists</a> / @Model.Artist.FullName
  </nav>
</div>

@await Html.PartialAsync("_SearchForm")

@if (!Model.Artist.IsApproved)
{
  <div class="">
    <p>Your submission is awaiting approval.</p>
  </div>
}

<div class="mb-10 bg-neutral-700 mr-4 lg:mr-8 rounded-sm p-4">
  <div class="flex gap-5 items-center">
    <picture>
      <source type="image/webp" srcset=@($"{Model.Artist.ImageUrl}.webp")>
      <source type="image/jpeg" srcset=@($"{Model.Artist.ImageUrl}.jpg")>

      <img class="rounded-full border border-neutral-500"
           src=@($"{Model.Artist.ImageUrl}.jpg")
           alt="@Model.Artist.ImageAlternateText"
           width="100"
           height="100"/>
    </picture>

    <div>
      <h1 class="font-open-sans text-neutral-200 uppercase">@Model.Artist.FullName</h1>
      <span class="font-open-sans text-neutral-400">@Model.LyricCount</span>
    </div>
  </div>
</div>

@if (Model.Lyrics.Any())
{
  <ul class="mr-4 lg:mr-8 mb-10">
    @foreach (var lyric in Model.Lyrics)
    {
      <li class="mb-4 bg-neutral-700 rounded-sm">
        <a class="p-4 flex justify-between items-center" asp-controller="Lyric" asp-action="Lyric"
           asp-route-artistSlug="@Model.Artist.PrimarySlug" asp-route-lyricSlug="@lyric.Slug">
          <h4 class="font-lora text-neutral-400">@lyric.Title</h4>

          <div class="flex gap-4">
            @if (lyric.IsVerified)
            {
              <i class="fa-kit fa-badge text-blue-500" title="Verified for accuracy"></i>
            }

            @if (lyric.IsAwaitingApproval)
            {
              <i class="fa-sharp fa-solid fa-hourglass-half text-neutral-400" title="Awaiting approval"></i>
            }
          </div>
        </a>
      </li>
    }
  </ul>
}

<div class="flex flex-col gap-y-4 pr-4 lg:pr-8 mb-6">
  @if (Model.Artist.IsEditable())
  {
    <a asp-controller="Artist"
       asp-action="Update"
       asp-route-artistSlug="@Model.Artist.PrimarySlug"
       class="bg-red-400 p-4 rounded-sm text-center font-open-sans text-base text-neutral-800 font-semibold">
      Update artist details
    </a>
  }

  <a asp-controller="Lyric"
     asp-action="Create"
     asp-route-artistSlug="@Model.Artist.PrimarySlug"
     class="bg-red-400 p-4 rounded-sm text-center font-open-sans text-base text-neutral-800 font-semibold">
    Add a lyric for @Model.Artist.FullName
  </a>
</div>

Bejebeje.Mvc/Views/Lyric/Create.cshtml
@model Bejebeje.Models.Lyric.CreateLyricViewModel

@{
  ViewData["Title"] = $"New lyric for {Model.Artist.FullName}";
  ViewData["Description"] = "Contribute to Kurdish Music and the archiving project by submitting a new lyric";
}

<div class="py-5 pr-4 mb-6">
  <nav class="text-neutral-200 opacity-70 uppercase text-base">
    <a asp-controller="Lyric" asp-action="ArtistLyrics"
       asp-route-artistSlug="@Model.Artist.PrimarySlug">/ @Model.Artist.FullName</a> / New Lyric
  </nav>
</div>

<div>
  <form asp-controller="Lyric" asp-action="Create" method="post" class="flex flex-col gap-6 pr-4 lg:pr-8">
    <div>
      <label class="block text-neutral-200 text-base font-open-sans mb-1">Title</label>
      <input asp-for="Title" class="p-4 w-full text-neutral-300 bg-zinc-700 rounded font-semibold"/>
    </div>

    <div>
      <label class="block text-neutral-200 text-base font-open-sans mb-1">Body</label>
      <textarea asp-for="Body" class="p-4 w-full text-neutral-300 bg-zinc-700 rounded font-semibold"
                rows="6"></textarea>
    </div>

    <input asp-for="Artist.Id" type="hidden"/>
    <input asp-for="Artist.PrimarySlug" type="hidden"/>

    <div>
      <p class="text-neutral-400 text-sm">Before adding the new lyric, please make sure the lyric does not already exist.</p>
    </div>

    <div class="flex flex-col gap-4 mb-8">
      <input type="submit" class="bg-red-400 p-4 rounded-sm text-center font-open-sans text-base text-neutral-800 font-semibold" value="Add lyric"/>
      <a asp-controller="Home" asp-action="Index" class="p-4 border border-b-neutral-400 rounded-sm text-center font-open-sans text-base text-neutral-200 font-semibold">Cancel</a>
    </div>
  </form>
</div>

Bejebeje.Mvc/Views/Lyric/Lyric.cshtml
@model Bejebeje.Models.Lyric.LyricDetailsViewModel

@{
  ViewData["Title"] = $"{Model.Artist.FullName} - {Model.Title} lyrics";
  ViewData["Description"] = $"Lyrics for {Model.Title} by {Model.Artist.FullName}. Gotinê strana {Model.Title} ya {Model.Artist.FullName}. {Model.Title} sözleri - {Model.Artist.FullName}";
}

<div class="py-5 pr-4 mb-6">
  <nav class="text-neutral-200 opacity-70 uppercase text-base">
    <a asp-controller="Lyric" asp-action="ArtistLyrics"
       asp-route-artistSlug="@Model.Artist.PrimarySlug">/ @Model.Artist.FullName</a> / @Model.Title
  </nav>
</div>

@await Html.PartialAsync("_SearchForm")

@if (!Model.IsApproved)
{
  <div class="">
    <p>Your submission is awaiting approval.</p>
  </div>
}

<a asp-controller="Lyric" asp-action="ArtistLyrics" asp-route-artistSlug="@Model.Artist.PrimarySlug"
   class="block mb-8 pr-4 lg:pr-8">
  <div class="flex gap-5 items-center bg-neutral-700 rounded-sm p-4">
    <picture>
      <source type="image/webp" srcset=@($"{Model.Artist.ImageUrl}.webp")>
      <source type="image/jpeg" srcset=@($"{Model.Artist.ImageUrl}.jpg")>

      <img class="rounded-full border border-neutral-500"
           src=@($"{Model.Artist.ImageUrl}.jpg")
           alt="@Model.Artist.ImageAlternateText"
           width="100"
           height="100"/>
    </picture>

    <div>
      <h1 class="text-neutral-200 font-open-sans uppercase">@Model.Artist.FullName</h1>
    </div>
  </div>
</a>

<div>
  <div>
    <h1 class="font-lora text-neutral-200 text-4xl mb-2">@Model.Title</h1>

    <div>
      <div class="flex gap-2 items-center">
        <p class="font-open-sans text-neutral-200 text-sm"><span class="opacity-70">By:</span> @Model.SubmitterUsername
        </p>
      </div>
    </div>
  </div>

  <div class="flex justify-between pr-4 lg:pr-8">
    <div class="mb-8">
      <div class="text-neutral-200 font-lora whitespace-pre-line mb-8">
        @Model.Body
      </div>

      @if (Model.Author.Id != null)
      {
        <a asp-controller="Author" asp-action="Get" asp-route-authorSlug="@Model.Author.PrimarySlug" class="bg-neutral-700 p-4 flex items-center gap-2 rounded-sm">
          <i class="fa-solid fa-pen-nib text-neutral-400"></i>
          <h6 class="text-neutral-200 font-semibold font-open-sans">
            <span class="text-neutral-400">Lyrics by:</span> @Model.Author.FullName
          </h6>
        </a>
      }
    </div>

    <div class="flex flex-col gap-4">
      @if (Model.IsVerified)
      {
        <i class="fa-kit fa-badge text-3xl lg:text-2xl text-blue-500" title="Verified for accuracy"></i>
      }

      <div class="flex flex-col items-center justify-center">
        @if (Model.AlreadyLiked)
        {
          <i class="fa-solid fa-heart text-3xl lg:text-2xl text-red-400" title="Lyric likes"></i>
        }
        else
        {
          <a asp-controller="Lyric"
             asp-action="Like"
             asp-route-artistSlug="@Model.Artist.PrimarySlug"
             asp-route-lyricSlug="@Model.PrimarySlug"
             asp-route-lyricId="@Model.Id">
            <i class="fa-solid fa-heart text-3xl lg:text-2xl text-neutral-500"></i>
          </a>
        }

        <p class="text-neutral-500 font-bold font-lora text-xl">@Model.NumberOfLikes</p>
      </div>
    </div>
  </div>
</div>