Bejebeje.Mvc/Controllers/ArtistController.cs
namespace Bejebeje.Mvc.Controllers;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bejebeje.Common.Extensions;
using Bejebeje.Models.Artist;
using Bejebeje.Mvc.ViewModels.Artists.CreateIndividualArtist;
using Bejebeje.Services.Services.Interfaces;
using Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Formats;
using SixLabors.ImageSharp.PixelFormats;

public class ArtistController : Controller
{
  private readonly IArtistsService _artistsService;

  public ArtistController(IArtistsService artistsService)
  {
    _artistsService = artistsService;
  }

  [Route("artists")]
  public async Task<IActionResult> Index()
  {
    IDictionary<char, List<LibraryArtistViewModel>> viewModel = await _artistsService
      .GetAllArtistsAsync();

    return View(viewModel);
  }

  [Authorize]
  [Route("artists/new/selector")]
  public IActionResult Selector()
  {
    return View();
  }

  [Authorize]
  [Route("artists/new/individual")]
  public IActionResult Create()
  {
    CreateIndividualArtistViewModel viewModel = new();

    return View(viewModel);
  }

  [Authorize]
  [HttpPost]
  [Route("artists/new/individual")]
  public async Task<IActionResult> Create(CreateIndividualArtistViewModel viewModel)
  {
    try
    {
      string userId = User.GetUserId().ToString();
      string firstName = viewModel.FirstName.Trim();
      string lastName = string.IsNullOrEmpty(viewModel.LastName) ? string.Empty : viewModel.LastName.Trim();
      string fullName = string.IsNullOrEmpty(lastName) ? firstName : $"{firstName} {lastName}";
      string artistSlug = fullName.NormalizeStringForUrl();
      var existingArtist = await _artistsService.GetArtistDetailsAsync(artistSlug, userId);

      // check for duplicate
      if (existingArtist != null)
      {
        viewModel.ExistingArtistFullName = fullName;
        viewModel.ExistingArtistSlug = existingArtist.PrimarySlug;
        viewModel.ExistingArtistImageUrl = existingArtist.ImageUrl;
        viewModel.ExistingArtistImageAlternateText = $"Photo of {existingArtist.FullName}";

        ViewBag.ArtistExists = true;
        return View(viewModel);
      }

      string turkishLetters = "ğıİöü";

      bool containsTurkishLetters = fullName.Any(c => turkishLetters.Contains(c, StringComparison.OrdinalIgnoreCase));

      // check for turkish letters
      if (containsTurkishLetters)
      {
        ModelState.AddModelError(string.Empty, "Are you sure you're adding Kurdish artists?");
        return View(viewModel);
      }

      if (viewModel.Photo != null)
      {
        // check image file size
        if (viewModel.Photo is { Length: > 500_000 })
        {
          ModelState.AddModelError(nameof(viewModel.Photo), "The photo size must not exceed 500KB.");
          return View(viewModel);
        }

        using Image<Rgba32> image = await Image.LoadAsync<Rgba32>(viewModel.Photo.OpenReadStream());

        if (image.Width > 1000 || image.Height > 1000)
        {
          ModelState.AddModelError(nameof(viewModel.Photo), "The photo must be at most 1000x1000 pixels.");
          return View(viewModel);
        }
      }

      CreateIndividualArtistDto dto = new()
      {
        FirstName = firstName,
        LastName = lastName,
        UserId = userId,
        Biography = viewModel.Biography.Trim(),
      };

      ArtistCreationResult result = await _artistsService
        .AddArtistAsync(dto);

      return RedirectToAction("ArtistLyrics", "Lyric", new { artistSlug = result.PrimarySlug });
    }
    catch
    {
      return View(viewModel);
    }
  }

  [Authorize]
  [Route("artists/{artistSlug}/update")]
  public async Task<IActionResult> Update(string artistSlug)
  {
    string userId = User.Identity.IsAuthenticated
      ? User.GetUserId().ToString()
      : string.Empty;

    ArtistViewModel artistViewModel = await _artistsService
      .GetArtistDetailsAsync(artistSlug, userId);

    if (string.IsNullOrEmpty(userId) || !artistViewModel.IsOwnSubmission ||
        !((DateTime.UtcNow - artistViewModel.CreatedAt).TotalDays < 2))
    {
      throw new Exception("User does not have access to update the artist.");
    }

    UpdateArtistViewModel viewModel = new UpdateArtistViewModel
    {
      Id = artistViewModel.Id,
      FirstName = artistViewModel.FirstName,
      LastName = artistViewModel.LastName,
    };

    return View(viewModel);
  }

  [Authorize]
  [HttpPost]
  [Route("artists/{artistSlug}/update")]
  public async Task<IActionResult> Update(UpdateArtistViewModel viewModel)
  {
    try
    {
      string userId = User.Identity.IsAuthenticated
        ? User.GetUserId().ToString()
        : string.Empty;

      ArtistViewModel artist = await _artistsService
        .GetArtistDetailsByIdAsync(viewModel.Id, userId);

      if (string.IsNullOrEmpty(userId) || !artist.IsOwnSubmission ||
          !((DateTime.UtcNow - artist.CreatedAt).TotalDays < 2))
      {
        throw new Exception("User does not have access to update the artist.");
      }

      ArtistUpdateResult result = await _artistsService
        .UpdateArtistAsync(viewModel);

      return RedirectToAction("ArtistLyrics", "Lyric", new { artistSlug = result.PrimarySlug });
    }
    catch
    {
      return View(viewModel);
    }
  }
}

Bejebeje.Mvc/Controllers/ProfileController.cs
namespace Bejebeje.Mvc.Controllers
{
  using Microsoft.AspNetCore.Authorization;
  using Microsoft.AspNetCore.Mvc;

  public class ProfileController : Controller
  {
    [Authorize]
    public IActionResult Index()
    {
      return View();
    }
  }
}

Bejebeje.Mvc/Controllers/SearchController.cs
namespace Bejebeje.Mvc.Controllers
{
  using System.Threading.Tasks;
  using Bejebeje.Models.Search;
  using Microsoft.AspNetCore.Mvc;
  using Services.Services.Interfaces;

  public class SearchController : Controller
  {
    private readonly ILyricsService _lyricsService;

    private readonly IArtistsService _artistsService;

    public SearchController(
      ILyricsService lyricsService,
      IArtistsService artistsService)
    {
      _lyricsService = lyricsService;
      _artistsService = artistsService;
    }

    [HttpGet]
    public IActionResult Index()
    {
      SearchViewModel viewModel = new SearchViewModel();

      return View(viewModel);
    }

    [HttpGet]
    public async Task<IActionResult> Search(string searchTerm)
    {
      SearchViewModel viewModel = new SearchViewModel();

      if (string.IsNullOrEmpty(searchTerm))
      {
        return View("Index", viewModel);
      }

      viewModel.SearchTerm = searchTerm;

      viewModel.Artists = await _artistsService
        .SearchArtistsAsync(searchTerm);

      viewModel.Lyrics = await _lyricsService
        .SearchLyricsAsync(searchTerm);

      return View("Index", viewModel);
    }
  }
}

Bejebeje.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" class="h-full">
<head>
  <!-- global site tag (gtag.js) - google analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-3XMV1NEC87"></script>
  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'G-3XMV1NEC87');
  </script>

  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>@ViewData["Title"] | Bêjebêje</title>
  <meta name="description" content="@ViewData["Description"]">
  <script src="https://kit.fontawesome.com/9d33bfa319.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="~/css/styles.css" media="screen"/>

  <link media="screen" rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  <link media="screen" rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link media="screen" rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link media="screen" rel="manifest" href="/site.webmanifest" crossorigin="use-credentials">
  <link media="screen" rel="mask-icon" href="/safari-pinned-tab.svg" color="#41414d">
  <meta name="msapplication-TileColor" content="#41414d">
  <meta name="theme-color" content="#41414d">
</head>

<body class="h-full m-0 grid relative grid-cols-[120px_auto] grid-rows-[auto_80px]">
<main
  class="pl-4 lg:pl-0 bg-neutral-800 lg:bg-transparent rounded-b-lg col-start-1 col-end-3 row-end-2 overflow-y-scroll lg:col-start-2 lg:row-start-1 lg:row-end-3 lg:grid lg:grid-rows-[auto_120px]">
  <div class="lg:bg-neutral-800 lg:pl-8 lg:rounded-bl-lg lg:row-start-1 lg:row-end-2">
    @RenderBody()
  </div>

  <div class="pr-4 lg:flex items-center justify-between row-start-2">
    <div class="mb-4 lg:mb-0 bg-neutral-950 lg:bg-transparent p-4 rounded flex items-center justify-between gap-4">
      <a href="https://www.facebook.com/bejebejefermi" class="">
        <i class="fa-brands fa-facebook-f text-neutral-600 lg:text-neutral-800 text-xl"></i>
      </a>

      <a href="https://twitter.com/bejebejefermi" class="">
        <i class="fa-brands fa-x-twitter text-neutral-600 lg:text-neutral-800 text-xl"></i>
      </a>

      <a href="https://www.youtube.com/channel/UCo7WnWABL3QiA1tErvs1w2w"
         class="">
        <i class="fa-brands fa-youtube text-neutral-600 lg:text-neutral-800 text-xl"></i>
      </a>

      <a href="https://www.instagram.com/bejebejefermi/" class="">
        <i class="fa-brands fa-instagram text-neutral-600 lg:text-neutral-800 text-xl"></i>
      </a>

      <a href="https://tiktok.com/@@bejebejefermi/" class="">
        <i class="fa-brands fa-tiktok text-neutral-600 lg:text-neutral-800 text-xl"></i>
      </a>
    </div>

    <div class="mb-8 lg:mb-0 flex justify-center">
      <p class="text-xs font-open-sans uppercase text-neutral-400 lg:text-neutral-800 lg:text-base opacity-80 tracking-wider">Bêjebêje &copy;
        2015-@(DateTime.UtcNow.Year)</p>
    </div>
  </div>
</main>

<nav class="col-start-1 col-end-3 row-start-2 flex items-center lg:block lg:col-end-2 lg:row-start-1 lg:row-end-3 lg:py-0 px-8 lg:pt-5">
  <ul class="flex justify-between lg:flex-col gap-6 w-full">
    <li>
      <a asp-controller="Home" asp-action="Index"
         class="flex flex-col justify-between items-center text-xs lg:text-sm gap-1.5">
        <i class="fa-kit fa-home text-lg lg:text-3xl text-neutral-800"></i>
        Home
      </a>
    </li>

    <li>
      <a asp-controller="Artist" asp-action="Selector" class="flex flex-col justify-between items-center text-xs lg:text-sm gap-1.5">
        <i class="fa-kit fa-contribute text-lg lg:text-3xl text-neutral-800"></i>
        Add
      </a>
    </li>

    <li>
      <a asp-controller="Profile" asp-action="Index"
         class="flex flex-col justify-between items-center text-xs lg:text-sm gap-1.5">
        <i class="fa-kit fa-user text-lg lg:text-3xl text-neutral-800"></i>
        Profile
      </a>
    </li>
  </ul>
</nav>

@RenderSection("Scripts", required: false)
</body>
</html>

Bejebeje.Mvc/Views/Shared/_SearchForm.cshtml
<div class="mb-5 lg:mb-8 w-full pr-4 lg:pr-8">
  <form asp-controller="Search" asp-action="Search" method="get" class="search__form">
    <input class="w-full bg-neutral-700 p-4 placeholder:text-neutral-200 placeholder:opacity-80 text-neutral-200 rounded-sm outline-0" placeholder="Search for artist or lyric" name="searchTerm" />
  </form>
</div>